// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjnfrfqscnpubnggmtew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqbmZyZnFzY25wdWJuZ2dtdGV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3Mjk5ODAsImV4cCI6MjA1ODMwNTk4MH0.Tco8cV5xMsWviO5uaK8Lxy8ti-Qs4KrSp2EfYgvQYHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);